services:
  db:
    image: postgres:latest
    container_name: pre-project24-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5435:5432"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    image: lildashik/pre-project5.4
    container_name: pre-project24-app
    ports:
      - "8082:8080"
    depends_on:
      - db
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge

volumes:
  db-data: