services:
  app:
    image: lildashik/pre-project5.4
    container_name: pre-project24-app
    ports:
      - "8082:8080"
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge