spring:
  application:
    name: SpringSecurity
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        id:
          new_generator_mappings: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
